apiVersion: v1
kind: Pod
metadata:
  name: fiap-multi-container

spec:
  containers:
    - name: nginx-container-1
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /data   
  volumes:
    - name: shared-data
      hostPath:
        path: /fiap/data
