apiVersion: v1
kind: Pod
metadata:
  name: api-js
  labels:
    app: api-js-redis
spec:
  containers:
    - name: apijslocal
      image: memarchi/fiap-api-redis:1.0
      ports:
        - containerPort: 3000
    - name: redis-server
      image: redis:latest
      ports:
        - containerPort: 6379
